name: DevSecOps CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-test-sast:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        cd app
        pip install -r requirements.txt

    - name: Run Unit Tests (optional)
      run: echo "Add test commands here"

    - name: Run Trivy Vulnerability Scan
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: './app'

    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: http://your-sonarqube-host

  docker-deploy-dast:
    needs: build-test-sast
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: |
        docker build -t devsecops-app ./app

    - name: Run App in Background
      run: |
        docker run -d -p 5000:5000 --name devapp devsecops-app
        sleep 10

    - name: Run OWASP ZAP Baseline Scan
      run: |
        docker run -t owasp/zap2docker-stable zap-baseline.py -t http://host.docker.internal:5000 -r zap-report.html

    - name: Upload ZAP Report
      uses: actions/upload-artifact@v2
      with:
        name: zap-report
        path: zap-report.html
